blank_issues_enabled: false
contact_links:
  - name: ‚ùì Ask a Question
    url: https://github.com/alshedivat/al-folio/discussions/categories/q-a
    about: Ask and answer al-folio related questions.
  - name: ‚ùì Ask a Question (Localization)
    url: https://github.com/george-gca/multi-language-al-folio/discussions/categories/q-a
    about: Ask and answer al-folio questions related to localization.
  - name: üìñ Read the documentation
    url: https://github.com/george-gca/multi-language-al-folio/blob/main/README.md
    about: Please consult the documentation before opening any issues!
