name: Prettier code formatter



on:
  push:
    branches:
      - gca
  workflow_dispatch:

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4
      - name: Install Prettier ðŸ’¾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Prettier Check ðŸ”Ž
        id: prettier
        run: npx prettier . --check
      - name: Show diff ðŸ“
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git diff > diff.txt
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt
          npm install -g diff-so-fancy
          git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
          git diff
      - name: Upload html diff
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: prettier_diff
          path: diff.html
            retention-days: 3